# Generated by Django 5.0.6 on 2024-07-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("qna", "0001_initial")]

    operations = [migrations.AddField(model_name="qna", name="file_upload", field=models.FileField(blank=True, null=True, upload_to="qna/files/"))]
