# Generated by Django 5.0.6 on 2024-06-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("video", models.FileField(upload_to="videos/")),
                ("sensor_log", models.FileField(upload_to="logs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
