# Generated by Django 5.0.6 on 2024-07-05 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Accident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("accident_date", models.DateField(auto_now_add=True)),
                ("accident_time", models.TimeField(auto_now_add=True)),
                ("accident_video", models.FileField(upload_to="record/videos/")),
                ("accident_location", models.TextField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("condition_date", models.DateField(auto_now_add=True)),
                ("condition_time", models.TimeField(auto_now_add=True)),
                ("condition_image", models.ImageField(upload_to="record/images/")),
                ("condition_location", models.TextField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
